apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-web-app-d
  namespace: jaya-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 20
  revisionHistoryLimit: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mavenapp
  template:
    metadata:
      labels:
        app: mavenapp
    spec:
      containers:
      - name: maven-web-app
        image: jaya462/java-application:1
        resources:
          requests:
            cpu: 250m
            memory: 300Mi
          limits:
            cpu: 600m
            memory: 500Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: jaya-ns
spec:
  type: NodePort
  selector:
    app: mavenapp
  ports:
  - port: 80
    targetPort: 8080

